# Generated by Django 3.2.6 on 2023-10-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(max_length=255)),
                ('participant_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('join_time', models.DateTimeField()),
                ('leave_time', models.DateTimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
