# Generated by Django 3.2.6 on 2023-10-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20231025_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoomparticipant',
            name='absent',
        ),
        migrations.RemoveField(
            model_name='zoomparticipant',
            name='leave',
        ),
        migrations.RemoveField(
            model_name='zoomparticipant',
            name='meeting_id',
        ),
        migrations.RemoveField(
            model_name='zoomparticipant',
            name='present',
        ),
        migrations.AddField(
            model_name='zoomparticipant',
            name='month',
            field=models.CharField(choices=[('PRESENT', 'present'), ('ABSENT', 'absent'), ('LEAVE', 'leave')], default='PRESENT', max_length=9),
        ),
        migrations.AlterField(
            model_name='zoomparticipant',
            name='leave_time',
            field=models.DateField(),
        ),
    ]
