# Generated by Django 3.2.6 on 2023-10-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_zoomparticipant_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zoomparticipant',
            old_name='leave_time',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='zoomparticipant',
            name='join_time',
        ),
    ]
